using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class camaracontroller : MonoBehaviour
{

    public Transform personaje;

    private float tama単oCamera;
    private float alturaPantalla;

    // Start is called before the first frame update
    void Start()
    {
        tama単oCamera = Camera.main.orthographicSize;
        alturaPantalla = tama単oCamera * 2;
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void Calcularpersonajecamara()
    {
        int pantallaPersonaje = (int)(personaje.position.y / alturaPantalla);
        float alturaCamara = (pantallaPersonaje * alturaPantalla) + tama単oCamera;

        transform.position = new Vector3(transform.position.x, alturaCamara, transform.position.z);
    }
}
